repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      # Lint and fix.  Fixes need manual inspecton.
      - id: ruff
        args: [ --fix ]
      # Format
      - id: ruff-format
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-file, ./pyproject.toml]
  # export python requirements
  - repo: https://github.com/pdm-project/pdm
    rev: 2.15.4
    hooks:
      - id: pdm-export
        args: [-o, requirements.txt, --without-hashes]
        files: ^pdm.lock$
  - repo: https://github.com/pdm-project/pdm
    rev: 2.15.4
    hooks:
      - id: pdm-lock-check
